var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,e,b){a instanceof String&&(a=String(a));for(var f=a.length,g=0;g<f;g++){var h=a[g];if(e.call(b,h,g,a))return{i:g,v:h}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,b){a!=Array.prototype&&a!=Object.prototype&&(a[e]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,e,b,f){if(e){b=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var g=a[f];g in b||(b[g]={});b=b[g]}a=a[a.length-1];f=b[a];e=e(f);e!=f&&null!=e&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");var cp_loadingpage=cp_loadingpage||{};
(function(){var a=cp_loadingpage,e={threshold:100,effect:"show",effectspeed:0,codeblock:"",loadingScreen:!0,removeInOnLoad:!1,graphic:"bar",backgroundColor:"#000",foregroundColor:"#fff",text:!0,deepSearch:!1,modifyDisplayRule:0,pageEffect:"none",onComplete:function(){"undefined"!=typeof window.afterCompleteLoadingScreen&&window.afterCompleteLoadingScreen()}},b=[],f=0,g=!1,h=0;a.extend=function(a,d){for(var c in d)d.hasOwnProperty(c)&&(a[c]=d[c]);return a};a.validateScreenSize=function(){var c=a.options;
if(!("screen_size"in c&&"all"!=c.screen_size&&"screen_width"in c))return!0;var d=parseFloat(c.screen_width);if(isNaN(d)||!isFinite(d))return!0;var b=document.documentElement;b=window.innerWidth||b.clientWidth;return"greater"==c.screen_size&&d<=b||"lesser"==c.screen_size&&b<=d};a.imgLoaded=function(a){return a.complete&&0!==a.naturalHeight};a.displayBody=function(){var c=jQuery('[id="loading-page-inline-style"]');c.length?c.remove():jQuery("html").append("<style>body{"+(1*a.options.modifyDisplayRule?
"display:block":"visibility:visible")+";}</style>")};a.loadOriginalImg=function(){jQuery("body").find(".lp-lazy-load").each(function(){var a=jQuery(this),d=a.attr("data-src"),b=a.attr("data-srcset");a.removeClass("lp-lazy-load");"undefined"!=typeof d&&a.attr("src",d);"undefined"!=typeof b&&a.attr("srcset",d)})};a.graphicAction=function(c,b){if("graphic"in a.options&&"graphics"in a&&a.options.graphic in a.graphics&&a.graphics[a.options.graphic].created)a.graphics[a.options.graphic][c](b)};a.ApplyAnimationToElement=
function(a){jQuery("body").addClass("lp-"+a)};a.onLoadComplete=function(){var c="undefined"==typeof lp_close_btn&&"additionalSeconds"in a.options&&jQuery.isNumeric(a.options.additionalSeconds)?parseInt(a.options.additionalSeconds):0,b=function(){jQuery("body").removeClass("lp_loading_screen_body");jQuery("#loading_page_codeBlock,.lp-close-screen").remove();a.graphicAction("complete",function(){a.ApplyAnimationToElement(a.options.pageEffect);a.options.onComplete();jQuery(document).trigger("loadingScreenCompleted")})};
c?setTimeout(function(){b()},1E3*c):b()};a.setLoadImgEvents=function(){for(var c=jQuery(window).height(),d=0,f=b.length;d<f;d++)if(!a.imgLoaded(b[d])){var e=jQuery(b[d]);if(a.options.deepSearch||e.offset().top<c)h++,e.on("load",function(){a.completeImageLoading()})}0==h&&this.completeImageLoading()};a.completeImageLoading=function(){f++;a.graphicAction("set",h?Math.min(f/h*100,100):100);h<=f&&!(1*a.options.removeInOnLoad)&&a.destroyLoader()};a.destroyLoader=function(){if(a.options.loadingScreen&&
!g){a.displayBody();var b=Math.min(h?f/h*100:0,100),d=function(){a.graphicAction("set",b);if(100==b)a.onLoadComplete();else b=Math.min(b+5,100),setTimeout(d,0)};g=!0;a.loadOriginalImg();d()}};a.loadingPage=function(){a.displayBody();b=jQuery("body").find("img:not(.lp-lazy-applied)");b.length&&a.setLoadImgEvents()};a.displayScreen=function(){jQuery(document).trigger("loadingScreenShow");if(a.options.closeBtn){var b=jQuery('<span class="lp-close-screen">X</span>');b.click(function(){lp_close_btn=!0;
if(g)a.onLoadComplete();else a.destroyLoader()});jQuery("html").append(b)}a.options.codeblock&&a.options.codeblock.length&&jQuery("html").append(a.options.codeblock);"undefined"!=typeof a.graphics&&"undefined"!=typeof a.graphics[a.options.graphic]&&(a.graphics[a.options.graphic].create(a.options),b=document.getElementById("loading_page_codeBlock"))&&(b.style.display="block")};a.options="undefined"!=typeof loading_page_settings?a.extend(e,loading_page_settings):e;a.options.text*=1;a.options.loadingScreen*=
1;a.options.loadingScreen&&a.validateScreenSize()?a.displayScreen():(a.displayBody(),a.options.loadingScreen=0)})();jQuery(function(){cp_loadingpage.options.loadingScreen&&cp_loadingpage.loadingPage()});jQuery(window).on("load",function(){cp_loadingpage.loadOriginalImg();cp_loadingpage.destroyLoader()});